version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: react-dnd
    versions:
    - 11.1.3
    - 13.0.0
    - 13.1.0
    - 13.1.1
    - 14.0.0
    - 14.0.1
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: react-dnd-html5-backend
    versions:
    - 11.1.3
    - 12.1.0
    - 12.1.1
  - dependency-name: bootstrap
    versions:
    - 4.5.1
  - dependency-name: json5
    versions:
    - 2.1.3
  - dependency-name: redux
    versions:
    - 4.0.5
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
